# for development
package_assets: <%= ENV['RAILS_ENV'] == 'test' ? 'off': 'on' %>
javascript_compressor: closure
compressor_options:
  compilation_level: "SIMPLE_OPTIMIZATIONS"

javascripts:
  lib:
    - public/javascripts/lib/jquery-1.6.1.js

stylesheets:
  global:
    - public/stylesheets/960.css
