# for development
javascripts:
  lib:
    - public/javascripts/lib/jquery-1.6.1.js

  app:

stylesheets:
  global:
    - public/stylesheets/reset.css
    - public/stylesheets/960.css

  app:
    - public/stylesheets/header_footer.css
    - public/stylesheets/global.css
    - public/stylesheets/constants.css

